[package]
name = "wasm-runtime"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wasm_runtime"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
hyperlight-common = { git = "https://github.com/mossaka/hyperlight", branch = "working-for-mcp", default-features = false }
hyperlight-guest = { git = "https://github.com/mossaka/hyperlight", branch = "working-for-mcp", features = [ "printf" ] }
wasmtime = { version = "32.0.0", default-features = false, features = [ "runtime", "component-model" ] }
hyperlight-wasm-macro = { path = "../hyperlight_wasm_macro" }
spin = "0.9.8"

[build-dependencies]
cc = "1.2"
cfg-if = { version = "1" }
cargo_metadata = "0.19"
reqwest =  {version = "0.12", default-features = false, features = ["blocking","rustls-tls"] }
